name: AI Code Reviewer
on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
permissions: write-all
jobs:
  review:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    name: Review Code
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Review
        uses: lukehollenback/ai-codereviewer@dev
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-3.5-turbo"
          exclude: "yarn.lock, dist/**, **/*.json, **/*.md, **/*.yaml, **/*.xml"
          custom_prompts: |
            Do not worry about the verbosity of variable names, as long as they are somewhat descriptive.
            Be sure to call out concurrency issues and potential race conditions.
            Do not worry about things a static analyzer would catch in real-time during development.
